{% set name = "torch_scatter" %}
{% set version = "2.0.8" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d71aab489b5288a6c96e9f9a7c9e13c54774dcb55a99a40e6cd1aca8be9ef3e6

build:
  number: 2
  string: h{{ PKG_HASH }}_{{ build_type }}_py{{ python | replace(".", "") }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }} #[build_type == 'cpu']
  string: h{{ PKG_HASH }}_{{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']
  skip: true  # [win]
  script:
    - export FORCE_CUDA="1"    # [linux64 and cudatoolkit  not in (undefined, 'None')]
    - export CC="$GCC"         # [linux64 and cudatoolkit  not in (undefined, 'None')]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cudatoolkit {{ cudatoolkit }}     # [build_type == 'cuda']
    - sysroot_linux-64 ==2.17                # [linux64]
    - python {{ python }}                  
    - pytorch-base {{ pytorch }}            

  host:
    - python {{ python }}
    - pip
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base {{ pytorch }} 
    - pytest-runner
  run:
    - python
    - cudatoolkit {{ cudatoolkit }}     # [build_type == 'cuda']
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base {{ pytorch }}

test:
  imports:
    - torch_scatter
about:
  home: https://github.com/rusty1s/pytorch_scatter
  summary: PyTorch Extension Library of Optimized Scatter Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_scatter

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
