{% set name = "torch_scatter" %}
{% set version = "2.1.1" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59b6fad2c04f58b4ea46bb56e839edfd421faaa849d5e32ab1290975b9ef1656

build:
  number: 1
  string: {{ build_type }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cpu']
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']
  skip: true  # [win]
  script:
    - export FORCE_CUDA="1"    # [build_type == 'cuda']
    - export CC="$GCC"         # [build_type == 'cuda']
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cudatoolkit {{ cudatoolkit }}     # [build_type == 'cuda']
    - sysroot_linux-64 ==2.17                # [linux64]
    - python {{ python }}                  
    - pytorch-base {{ pytorch }}            

  host:
    - python {{ python }}
    - pip
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base {{ pytorch }} 
    - pytest-runner
  run:
    - python
    - cudatoolkit {{ cudatoolkit }}     # [build_type == 'cuda']
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base {{ pytorch }}

test:
  imports:
    - torch_scatter
about:
  home: https://github.com/rusty1s/pytorch_scatter
  summary: PyTorch Extension Library of Optimized Scatter Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_scatter

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
