{% set name = "torch_scatter" %}
{% set version = "2.0.8" %}
# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
#{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}
{% if build_type == 'cpu' %}
   {% set torch_proc_type = "cpu" %}
{% elif build_type == "cuda" %}
   {% set torch_proc_type = "cuda" %}
{% endif %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d71aab489b5288a6c96e9f9a7c9e13c54774dcb55a99a40e6cd1aca8be9ef3e6

build:
  number: 1
{% if build_type == 'cpu' %}
  string: h{{ PKG_HASH }}_{{ build_type }}_py{{ python | replace(".", "") }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
{% else %}
  string: h{{ PKG_HASH }}_{{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
{% endif %}
  skip: true  # [win]
  script:
    - export FORCE_CUDA="1"    # [linux64 and cudatoolkit  not in (undefined, 'None')]
    - export CC="$GCC"         # [linux64 and cudatoolkit  not in (undefined, 'None')]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 ==2.17                # [linux64]
    - python {{ python }}                  
    - cross-python_{{ target_platform }}   
    - pytorch-base {{ pytorch }}            

  host:
    - python {{ python }}
    - pip
    - pytorch-base {{ pytorch }} 
    - pytest-runner
  run:
    - python 
    - pytorch-base {{ pytorch }}

test:
  imports:
    - torch_scatter
about:
  home: https://github.com/rusty1s/pytorch_scatter
  summary: PyTorch Extension Library of Optimized Scatter Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_scatter

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
